### ISSUE TITLE
Location link not displaying

### ISSUE THREAD

**Issue by a-thomas-ny** [IEEEKeralaSection/rescuekerala#552]
### Subject of the issue
Location tagged by the user is not accessible

### Your environment
* version of your python
* which browser and its version
* OS Type (iOS/Android/Linux/Windows)

### Steps to reproduce
https://keralarescue.in/request_details/37978/
called the user, he confirmed the location link was entered but not listed in the details. 3 families and children stuck there but without location link, request cannot be passed to Army.

### Expected behaviour
Tell us what and how exactly is it supposed to  happen

### Actual behaviour
Tell us what happens instead or what went wrong

**Comment by SajinSabu** [comment]
Is it fixed by now?

**Comment by pranavashok** [comment]
This is still not fixed. See https://github.com/IEEEKeralaSection/rescuekerala/pull/600#issuecomment-414067721
