### ISSUE TITLE
Manually entered location not displayed in request details page

### ISSUE THREAD

**Issue by pranavashok** [IEEEKeralaSection/rescuekerala#607]
### Subject of the issue
Location entered manually in the /request autocomplete form is not displayed on the /request_details page.

### Your environment
* Python3
* Firefox
* Linux

### Steps to reproduce

![x1](https://user-images.githubusercontent.com/930537/44301179-ca165480-a312-11e8-87ee-50ffcf53f3d3.png)

![x2](https://user-images.githubusercontent.com/930537/44301180-cc78ae80-a312-11e8-953d-f60072cb9470.png)

### Expected behaviour
GPS details on the /request_details must contain something other than NA

### Actual behaviour
GPS details on the /request_details page contains NA

**Comment by pranavashok** [comment]
#600 and #608 fixes this.

**Comment by bobinson** [comment]
@pranavashok just confirming, this issue is fixed right ?

**Comment by pranavashok** [comment]
@bobinson No, its not fixed. #600 made the GPS location come in the DB and #608 will display it on the /request_details page.

**Comment by liginv** [comment]
wouldn't  django-geoposition library can fix this?

**Comment by liginv** [comment]
This is modified to fit django 2.X
[django-geoposition-0.3.1.tar.gz](https://github.com/IEEEKeralaSection/rescuekerala/files/2299803/django-geoposition-0.3.1.tar.gz)
